#!/usr/bin/env python3
"""Configure Codex/Claude rules that route to canonical AGENTS OS skills."""

from __future__ import annotations

import argparse
import os
import shutil
import sys
from pathlib import Path


START = "<!-- AGENTS_OS_MANAGED_START -->"
END = "<!-- AGENTS_OS_MANAGED_END -->"
ADAPTER_MARKER = "<!-- Generated by AGENTS OS install-skill-adapters.py -->"


def managed_block(vault: Path, global_scope: bool) -> str:
    scope = "en cualquier proyecto" if global_scope else "mientras trabajas en este vault"
    if global_scope:
        root_resolution = """Resuelve `VAULT_ROOT` desde `$AGENTS_OS_VAULT`; si no está
   definido, lee `~/.config/agents-os/vault-root`; como último fallback usa el
   workspace actual cuando contenga `80-agents/agents-os/agents-os.md`. Si
   ninguno resuelve el marker, informa instalación no disponible y no inventes
   una ruta."""
    else:
        root_resolution = """Resuelve `VAULT_ROOT` desde el workspace actual: es la carpeta
   que contiene `80-agents/agents-os/agents-os.md`. Si no existe ese marker,
   estas reglas no aplican."""
    return f"""{START}
Al iniciar una nueva sesión que use AGENTS OS {scope}, ejecuta bootstrap una sola vez:

1. {root_resolution} Invoca
   `80-agents/skills/agents-os-bootstrap/SKILL.md` desde esa raíz y léelo completo sólo en cold start. No vuelvas a invocarlo por cada mensaje. En turnos warm reutiliza la base; si cambia la entidad, ejecuta únicamente el routing de cambio de entidad y recupera su delta.
2. Las únicas skills canónicas viven en `80-agents/skills/`, relativo a
   `VAULT_ROOT`. Cuando bootstrap seleccione una skill, lee completamente su
   `SKILL.md` y ejecútala desde ahí. No copies, enlaces ni generes skills bajo
   carpetas de Codex o Claude.
3. Trata Markdown como fuente de verdad y Graphify como índice derivado.
4. No cierres una sesión de AGENTS OS salvo pedido explícito del usuario.

Estas reglas son duras. Bootstrap decide cold/warm/cambio de entidad y carga
solo el contexto suficiente; no reemplaces ese routing con una lectura amplia
del vault.
{END}"""


def update_managed_file(path: Path, block: str, dry_run: bool) -> None:
    if path.exists():
        content = path.read_text(encoding="utf-8")
    else:
        content = "# AGENTS.md\n\n<INSTRUCTIONS>\n</INSTRUCTIONS>\n"

    if START in content or END in content:
        if content.count(START) != 1 or content.count(END) != 1:
            raise SystemExit(f"managed markers are malformed in {path}")
        before, rest = content.split(START, 1)
        _, after = rest.split(END, 1)
        updated = before.rstrip() + "\n" + block + after
    elif "</INSTRUCTIONS>" in content:
        updated = content.replace("</INSTRUCTIONS>", block + "\n</INSTRUCTIONS>", 1)
    else:
        updated = content.rstrip() + "\n\n" + block + "\n"

    if dry_run:
        print(f"Would update rules: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(updated, encoding="utf-8")
    print(f"Updated rules: {path}")


def ensure_claude_import(path: Path, dry_run: bool) -> None:
    content = path.read_text(encoding="utf-8") if path.exists() else ""
    if "@AGENTS.md" in content:
        print(f"Claude import already present: {path}")
        return
    updated = "@AGENTS.md\n\n" + content.lstrip()
    if dry_run:
        print(f"Would add @AGENTS.md import: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(updated, encoding="utf-8")
    print(f"Added @AGENTS.md import: {path}")


def update_vault_pointer(path: Path, vault: Path, dry_run: bool) -> None:
    if dry_run:
        print(f"Would update vault pointer: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"{vault}\n", encoding="utf-8")
    print(f"Updated vault pointer: {path}")


def remove_generated_adapters(target: Path, dry_run: bool) -> None:
    if not target.is_dir():
        return
    generated = []
    for skill_file in target.glob("*/SKILL.md"):
        if ADAPTER_MARKER in skill_file.read_text(encoding="utf-8"):
            generated.append(skill_file.parent)
    for directory in generated:
        if dry_run:
            print(f"Would remove generated adapter: {directory}")
        else:
            shutil.rmtree(directory)
            print(f"Removed generated adapter: {directory}")
    if not dry_run and target.is_dir() and not any(target.iterdir()):
        target.rmdir()


def validate_vault(vault: Path) -> None:
    required = [
        vault / "80-agents" / "agents-os" / "agents-os.md",
        vault / "80-agents" / "agents-os" / "agent-constitution.md",
        vault / "80-agents" / "skills" / "agents-os-install" / "SKILL.md",
    ]
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        raise SystemExit("not an installable AGENTS OS vault; missing: " + ", ".join(missing))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--vault", type=Path, required=True)
    parser.add_argument(
        "--surface", choices=("codex", "claude", "both"), default="both"
    )
    parser.add_argument(
        "--scope", choices=("project", "global"), default="project"
    )
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    vault = args.vault.expanduser().resolve()
    validate_vault(vault)

    selected = {"codex", "claude"} if args.surface == "both" else {args.surface}
    global_scope = args.scope == "global"
    block = managed_block(vault, global_scope)

    update_managed_file(vault / "AGENTS.md", block, args.dry_run)
    if "claude" in selected:
        ensure_claude_import(vault / "CLAUDE.md", args.dry_run)

    remove_generated_adapters(vault / ".agents" / "skills", args.dry_run)
    remove_generated_adapters(vault / ".claude" / "skills", args.dry_run)

    if global_scope:
        home = Path.home()
        update_vault_pointer(home / ".config" / "agents-os" / "vault-root",
                             vault, args.dry_run)
        if "codex" in selected:
            codex_home = Path(os.environ.get("CODEX_HOME", home / ".codex")).expanduser()
            update_managed_file(codex_home / "AGENTS.md", block, args.dry_run)
            remove_generated_adapters(home / ".agents" / "skills", args.dry_run)
        if "claude" in selected:
            claude_agents = home / ".claude" / "AGENTS.md"
            update_managed_file(claude_agents, block, args.dry_run)
            ensure_claude_import(home / ".claude" / "CLAUDE.md", args.dry_run)
            remove_generated_adapters(home / ".claude" / "skills", args.dry_run)

    print(
        f"Configured rules for surfaces={','.join(sorted(selected))} "
        f"scope={args.scope} canonical_skills={vault / '80-agents' / 'skills'}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
